services:
  mongo:
    image: mongo:4
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}

volumes:
  mongo-data:
