name: Create Pull Request

on:
  push:
    branches:
      - 'dev/**'

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Tests
        run: |
          echo "This is a test"
          # Simulate test command
          echo "Tests passed."

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
          gh pr create --title "PR: Feature Branch $BRANCH_NAME" --body "Automated PR from feature branch $BRANCH_NAME" --head $BRANCH_NAME --base main --label "feature-branch"