name: Create Pull Request

on:
  push:
    branches:
      - 'dev/**'

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Tests
        run: |
          echo "This is a test"
          # Simulate test command
          echo "Tests passed."

      - name: Create PR if tests pass
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = context.ref.replace('refs/heads/', '');
            github.pulls.create({
              owner: owner,
              repo: repo,
              title: `PR: Feature Branch ${branch}`,
              head: branch,
              base: 'main',
              body: `Automated PR from feature branch ${branch}`,
              labels: ['feature-branch']
            })
